### ISSUE TITLE
Add support of JSON encoded strings as input/output

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#20]
It have deferred this issue to question because using a string for input and output is:
1) error prone due standard Java decoders by default replaces malformed bytes by placeholder characters, and encoders ignores invalid surrogate pairs
2) inefficient, and conversion of the string from bytes or to bytes takes about the same time as parsing or serialization of JSON immediately from bytes to data structures or back

**Comment by nilskp** [comment]
Many APIs expect a `String`, so it would be better to have a default UTF-8 conversion built-in rather than kick the problem down to every developer.

**Comment by plokhotnyuk** [comment]
@nilskp are they OSS APIs? Please post here a couple of examples.

**Comment by nilskp** [comment]
@plokhotnyuk I use Jetty a lot. 

For SSE, the Emitter interface:
https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/servlets/EventSource.Emitter.html

But I think a larger point is that JSON *is* a text format, not a binary format. Treating it as binary is of course possible, as it is with any kind of data, but it's not its natural state.
There are advantages to staying binary for some use cases, but that shouldn't exclude the proper data type, which is simply a UTF-8 string.

**Comment by shawjef3** [comment]
A UTF-8 encoded string is certainly the correct internal representation for encoded JSON. A JSON serializer that only exposes Array[Byte] as the serialized representation is certainly above any criticism when it comes to performance or character encoding.

On the other hand, using Java's built-in UTF-8 encoders to add little functions that do the same things but give and take Strings is worthy of some praise. Any Unicode encoding problems are the responsibility of the JVM, not this library. It will be no more incorrect than what everyone who needs the JSON as a String is already going to do, and it will encourage adoption. Finally, people who absolutely must have the best performance will see comments in the code saying to use the Array[Byte] versions of the functions instead.

I want to add that Java 9 uses Array[Byte] for Strings that contain only Chars in the LATIN1 character set, so that should mitigate some of your performance worries. See [http://openjdk.java.net/jeps/254](http://openjdk.java.net/jeps/254).

**Comment by plokhotnyuk** [comment]
Finally the reasonable case to have parsing/serialization from/to string was found and feature was implemented. 

But it is not recommended for everyday usage still :)

See details here: #224
