### ISSUE TITLE
Deserialize to JSON AST

### ISSUE THREAD

**Issue by carymrobbins** [plokhotnyuk/jsoniter-scala#437]
Is there any way to deserialize to a JSON AST? Sometimes you may just have some arbitrary JSON object that has an undefined schema and you want to just allow any valid JSON object.

**Comment by carymrobbins** [comment]
Here's an example. I'd prefer to not have to keep up with every error type. I would rather have a type like this -

```scala
final case class HsDevError(
  error: String,
  body: JSONObject
)

readFromString(""" { "error": "foo", "bar": "baz", "spam": "eggs" } """)
// HsDevError("foo", """{"error":"foo","bar":"baz","spam":"eggs"}""")
```

Instead, at the moment, I have to handle every case, which also makes it tough to keep up with in case new cases are added later.

```scala
sealed trait HsDevError
object HsDevError {
  final case class HsDefFailure()
  final case class ModuleNotSource(module: HsDevModuleLocation) extends HsDevError
  final case class BrowseNoModuleInfo(module: String) extends HsDevError
  final case class FileNotFound(file: String) extends HsDevError
  final case class ToolNotFound(tool: String) extends HsDevError
  final case class ProjectNotFound(project: String) extends HsDevError
  final case class PackageNotFound(`package`: String) extends HsDevError
  final case class ToolError(tool: String, msg: String) extends HsDevError
  final case class NotInspected(module: HsDevModuleLocation) extends HsDevError
  final case class InspectError(msg: String) extends HsDevError
  final case class InspectCabalError(cabal: String, msg: String) extends HsDevError
  final case class IOFailed(msg: String) extends HsDevError
  final case class GhcError(msg: String) extends HsDevError
  final case class RequestError(msg: String, request: String) extends HsDevError
  final case class ResponseError(msg: String, response: String) extends HsDevError
  final case class SQLiteError(msg: String) extends HsDevError
  final case class OtherError(msg: String) extends HsDevError
  final case class UnhandledError(msg: String) extends HsDevError

  implicit val jsonCodec: JsonValueCodec[HsDevError] =
    JsonCodecMaker.make(
      CodecMakerConfig
        .withDiscriminatorFieldName(Some("error"))
        .withAdtLeafClassNameMapper {
          case "HsDefFailure" => "failure"
          case "ModuleNotSource" => "module is not source"
          case "BrowseNoModuleInfo" => "no module info"
          case "FileNotFound" => "file not found"
          case "ToolNotFound" => "tool not found"
          case "ProjectNotFound" => "project not found"
          case "PackageNotFound" => "package not found"
          case "ToolError" => "tool error"
          case "NotInspected" => "module not inspected"
          case "InspectError" => "inspect error"
          case "InspectCabalErr" => "inspect cabal error"
          case "IOFailed" => "io error"
          case "GhcError" => "ghc error"
          case "RequestError" => "request error"
          case "ResponseError" => "response error"
          case "SQLiteError" => "sqlite error"
          case "OtherError" => "other error"
          case "UnhandledError" => "unhandled error"
        }
    )
}
```

**Comment by plokhotnyuk** [comment]
@carymrobbins Hi, Cary!

Short answer: yes, it is possible, but jsoniter-scala does not provide any built-in default AST (mostly due safety and efficiency reasons that will be explained below). 

[Here](https://github.com/pathikrit/dijon/blob/181b6ac29f179ad685f564b996d8738d1a5bd375/src/main/scala/com/github/pathikrit/dijon/package.scala#L148-L205) and [here](https://github.com/plokhotnyuk/jsoniter-scala/pull/424/files#diff-676e94ffb8bec3df03f65260dca15267R103-R179) are a couple of examples of how a custom codec can be defined for 3rd-party ASTs.

Building, holding, and accessing of hash maps and boxed values are much expensive than case classes and primitives.

Weakest places of most ASTs that in case of untrusted input make them vulnerable under DoS/DoW attacks which exploit:
1) [default Scala's hash maps have `O(n^2)` complexity of insertion in case of hash collision](https://github.com/scala/bug/issues/11203);
2) [parsing of Scala's/Java's `BigInt/BigInteger` values from string representation has `O(n^2)` complexity, and can be exponential for using of parsed `BigDecimal` with big exponent in subsequent arithmetic operations](https://stackoverflow.com/a/58777171/228843);
3) stack overflow exception because using of non-tail recursion in [most implementations of codecs for ASTs](https://github.com/lovasoa/bad_json_parsers).

Also, have you considered to use custom codecs for parsing errors to some limited number of case classes or using [jsoniter-scala's feature of parsing/serialization of raw JSON values](https://github.com/plokhotnyuk/jsoniter-scala/blob/209d918a030b188f064ee55505a6c47257731b4b/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L644-L673)?

**Comment by carymrobbins** [comment]
Oh, your `RawVal` example in the last link looks perfect, thanks!
