### ISSUE TITLE
Wrong ZonedDateTime handling

### ISSUE THREAD

**Issue by octavz** [plokhotnyuk/jsoniter-scala#547]
Hi,

I found some issue with `ZonedDateTime` ser/de:

```scala
implicit val zonedDateTimeCodec = JsonCodecMaker.make[ZonedDateTime]
writeToString(readFromString[ZonedDateTime](""""2020-04-10T10:07:00.000Z""""))
```
will return `"2020-04-10T10:07Z"` 

How can I make it return the original value?
IMHO this is a bug, since `10:07` is not the same thing as `10:07:00`

Thank You

**Comment by plokhotnyuk** [comment]
Currently the content of strings for serialized `java.time.*` values matches with their .toString:
```
$ scala
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> java.time.ZonedDateTime.parse("2020-04-10T10:07:00.000Z").toString
res0: String = 2020-04-10T10:07Z
```
To alter the result of encoding you can define an implicit instance using a custom codec for the java.time.ZonedDateTime type so that it will be picked by derivation macros, like [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/7cf547cfb13dfacd3be3759b603426432202a5b9).
